### PR TITLE
Revise Japanese translations

### PR DESCRIPTION
**Pull request by TonalidadeHidrica**
Thank you for the wonderful Japanese version!  I enjoyed the game.

I revised some Japanese messages, from the native's point of view.
Overall there was no problem, and I just make it more fluent.

Was this translation made by machine translation or are you are a Japanese learner?  If latter, and if you are interested in, feel free to ask anything about why it hears more fluent for natives!

### CODE REVIEW

**Comment by taximanli** [comment]
Special thanks to Tonalidade Hidrica for taking time to revise the Japanese messages.

**Comment by taximanli** [comment]
@TonalidadeHidrica Could I ask you what is the natural Japanese translation for the error message "Share failed" appeared when copying results to clipboard?

**Comment by TonalidadeHidrica** [comment]
@taximanli "シェアに失敗しました" would be nice.

**Comment by taximanli** [comment]
@TonalidadeHidrica Thank you for your continuous support on this Japanese version!
I've recently updated the game. Would you mind sparing your time to help revise my Japanese translation?
I tried to translate it to sound natural but I'm still learning :)

The Japanese texts are in these two files
/src/constants/strings.ts
/src/components/modals/InfoModal.tsx

**Comment by TonalidadeHidrica** [comment]
Sure thing!  I'll check it up in a couple of days.

**Pull request merged**
